### ISSUE TITLE
TypeError: plugin.apply is not a function

### ISSUE THREAD

**Issue by fivecakes** [nkjmsss/markdown-it-color#7]
![image](https://user-images.githubusercontent.com/16848852/107116536-e295d300-68ae-11eb-8007-6474556ca6e6.png)

**Comment by nkjmsss** [comment]
If you still struggling with this issue, please give me more detailed information. It's too hard for me to debug.

**Comment by diogotcorreia** [comment]
@nkjmsss Here is some more detailed information and a test repository.

I reproduced this with VuePress. After installing this, the following is printed to the terminal on `yarn dev`.

```
❯ yarn dev
yarn run v1.22.10
$ vuepress dev src
wait Extracting site metadata...
tip Apply theme @vuepress/theme-default ...
warning An error was encountered in plugin "@vuepress/plugin-back-to-top"
warning An error was encountered in plugin "@vuepress/plugin-medium-zoom"
tip Apply plugin container (i.e. "vuepress-plugin-container") ...
tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
tip Apply plugin @vuepress/active-header-links (i.e. "@vuepress/plugin-active-header-links") ...
tip Apply plugin @vuepress/search (i.e. "@vuepress/plugin-search") ...
tip Apply plugin @vuepress/nprogress (i.e. "@vuepress/plugin-nprogress") ...
TypeError: plugin.apply is not a function
    at MarkdownIt.use (/home/user/Documents/test-markdown-it-color/docs/node_modules/markdown-it/lib/index.js:496:10)
    at extendMarkdown (/home/user/Documents/test-markdown-it-color/docs/src/.vuepress/config.js:72:10)
    at afterInstantiate (/home/user/Documents/test-markdown-it-color/docs/node_modules/@vuepress/core/lib/node/createMarkdown.js:23:23)
    at module.exports (/home/user/Documents/test-markdown-it-color/docs/node_modules/@vuepress/markdown/index.js:125:23)
    at module.exports (/home/user/Documents/test-markdown-it-color/docs/node_modules/@vuepress/core/lib/node/createMarkdown.js:27:10)
    at App.process (/home/user/Documents/test-markdown-it-color/docs/node_modules/@vuepress/core/lib/node/App.js:113:21)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async dev (/home/user/Documents/test-markdown-it-color/docs/node_modules/@vuepress/core/lib/index.js:17:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Test repo is available at https://github.com/diogotcorreia/test-markdown-it-color/tree/master/docs.

This is the commit that added it: https://github.com/diogotcorreia/test-markdown-it-color/commit/31da0504a42ee7d8f010bfecbe23ff299e2c48ce

These are VuePress' docs on markdown-it plugins: https://vuepress.vuejs.org/guide/markdown.html#advanced-configuration

**Comment by nkjmsss** [comment]
I created this library for `import / export`, not for `exports / require`. Therefore, you need to import as `require('markdown-it-color').default`.

It may seem odd to you and sorry for inconvenience. If you are familiar with, please tell me better way of building a lib.

**Comment by diogotcorreia** [comment]
Thanks!
That fixes the problem for me. I'll see if I can make a PR that fixes that.
